### ISSUE TITLE
Get At Me

### ISSUE THREAD

**Issue by derek-adair** [gatlin/torc#1]
I need your business experience desperately.  I'm setting up an employee owned not-for-profit software firm who seeks to build good software (in every sense of the word).

~CALL ME~ probably just email me actually it was dumb to post my # lol --------- d[at]derekadair.com

**Comment by gatlin** [comment]
You flatter me! My experience in business is that I'm a failure and I can't imagine what I know that you don't. That being said of course if I can help a friend I will try. You may not want to post your number here though!

On October 6, 2023 7:55:02 AM CDT, Derek ***@***.***> wrote:
>I need your business experience desperately.  I'm setting up an employee owned not-for-profit software firm who seeks to build good software (in every sense of the word).
>
>CALL ME....
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/gatlin/torc/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by derek-adair** [comment]
Those of us who are not blessed to see the luck of capitalism play out for us all feel like failures.  The meritocracy is fake tho... so...

![che-guevara-pd jpg__600x768_q85_crop_subsampling-2](https://github.com/gatlin/torc/assets/847236/0f065c7f-f14d-4e83-88b3-ddf61efabef1)

**Comment by derek-adair** [comment]
Anyways do you have time to talk this week? I am... really bad at paperwork and don't even really know what paperwork to do for this kinda crap so I would greatly appreciate some of your time to pick your brain on how/what/where to go from here and all that.

Also if the implication that I would like for you to be one of the first workers for this firm should not be lost on you.  I think you will vibe w/ the overall mission I'm trying to accomplish.  [Read the fluff here.](https://adairsoftware.com)

**Comment by derek-adair** [comment]
I have been got.
